VAGRANTFILE_API_VERSION = "2"

unless Vagrant.has_plugin?("vagrant-disksize")
  puts 'Installing vagrant-disksize Plugin...'
  system('vagrant plugin install vagrant-disksize')
end

unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "ubuntudev" , primary: true do |ubuntudev|
  ubuntudev.vm.box = "ubuntu/bionic64"
  ubuntudev.vm.hostname = "ubuntudev"
  ubuntudev.disksize.size = '75GB'
  ubuntudev.vbguest.auto_update = true
  config.vm.network "forwarded_port", guest: 8080, host: 8180
  # Create a private network, which allows host-only access to the machine
  # using a specific IP - I have arbitrarily decided on 192.168.188.142. Feel free to change this
  config.vm.network "private_network", ip: "192.168.188.142"
  
  ubuntudev.vm.provider :virtualbox do |vb|
	  vb.default_nic_type = "Am79C973"
    # depending on how much RAM your physical host machine has, you may need to adjust this memory setting; note: for generating a native image, a lot of memory is required in the VM
	  #vb.customize ["modifyvm"     , :id, "--memory", "16384"]
	  vb.customize ["modifyvm"     , :id, "--memory", "8384"]
    vb.customize ["modifyvm"     , :id, "--name"  , "GraalVM Polyglot workshop"]
    vb.customize ["modifyvm"     , :id, "--cpus"  , 6]
	  vb.customize ["modifyvm"     , :id, "--clipboard","bidirectional"]
	  vb.customize ["modifyvm"     , :id, "--vram","16"]
  end
	
  #this starts provisioning the machine
  ubuntudev.vm.provision :shell, path: "provision.sh"
  end
end
